" mostly from https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim

" unlimited undo
set nocompatible

" when a file is read from outside
set autoread

" Show matching brackets when text indicator is over them
set showmatch
set mat=2

" always show the status line
set laststatus=2
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c:q


" so we can use bnext without !
set hidden

set ruler
set cmdheight=2

syntax on
filetype plugin on
filetype indent on

set history=500

" Use spaces instead of tabs
set expandtab
set smarttab
" 1 tab == 4 spaces
set shiftwidth=2
set tabstop=2
" fix backspace
set backspace=indent,eol,start

set ai "auto indent
set si "smart indent
set wrap "wrap lines

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Turn on the Wild menu
set wildmenu
set wildignore=*.o,*~,*.pyc,*.class

" incremental search, like in other editors
set incsearch

" performance boost when running macros
set lazyredraw

" stop annoying me
set noerrorbells
set novisualbell
set t_vb=
set tm=500

set encoding=utf8
set ffs=unix,dos,mac

" since we use version control system
set nobackup
set nowb
set noswapfile

set scrolloff=5

let mapleader = ","

nmap <leader>w :w!<cr>

nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> [B :bfirst<CR>
nnoremap <silent> ]B :blast<CR>

" Close the current buffer
map <leader>bd :Bclose<cr>:tabclose<cr>gT

" Close all the buffers
map <leader>ba :bufdo bd<cr>

map <leader>l :bnext<cr>
map <leader>h :bprevious<cr>

" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader>nt :tabnext
map <leader>pt :tabprevious
nnoremap <Leader>ve :e $MYVIMRC<CR>
nnoremap <Leader>vr :source $MYVIMRC<CR>

source $ENV_BASE_DIR/etc/vim/colors.vim

" Returns true if paste mode is enabled
function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    endif
    return ''
endfunction


" Don't close window, when deleting a buffer
command! Bclose call <SID>BufcloseCloseIt()
function! <SID>BufcloseCloseIt()
    let l:currentBufNum = bufnr("%")
    let l:alternateBufNum = bufnr("#")

    if buflisted(l:alternateBufNum)
        buffer #
    else
        bnext
    endif

    if bufnr("%") == l:currentBufNum
        new
    endif

    if buflisted(l:currentBufNum)
        execute("bdelete! ".l:currentBufNum)
    endif
endfunction

