;;Customize colors (To see the font lock applying to a point Ctrl-u Ctrl-x =)
(set-face-foreground 'font-lock-string-face "#76CB58")
(set-face-foreground 'font-lock-comment-face "#629755")
(set-face-foreground 'font-lock-keyword-face "#CC7832")
(set-face-foreground 'font-lock-function-name-face "#3E7EFF")
(set-face-foreground 'font-lock-variable-name-face "#FFC66D")
(set-face-foreground 'font-lock-warning-face "#FFC66D")
(set-face-foreground 'font-lock-type-face "#A9B7C6")
(set-face-foreground 'font-lock-builtin-face "#BBB529")
(set-face-foreground 'font-lock-constant-face "#6897BB")
(set-background-color black)
(set-foreground-color white)
